# -*- coding: utf8 -*-

import logging

# service variant name and default value
SERVICE_CONFIG_MODULE = 'service'
SERVICE_ENV = 'ENV'
SERVICE_HOST = 'HOST'
SERVICE_PORT = 'PORT'
SERVICE_DEBUG = 'DEBUG'
SERVICE_LOG_LEVEL = 'LOG_LEVEL'
SERVICE_BASE_URL = 'BASE_URL'
SERVICE_SECRET_KEY = 'SECRET_KEY'
SERVICE_DOMAIN = 'DOMAIN'

SERVICE_DEFAULT_ENCODING = 'utf8'
SERVICE_DEFAULT_CONFIG = 'default_local.ini'
SERVICE_DEFAULT_ENV = 'local'
SERVICE_DEFAULT_HOST = '0.0.0.0'
SERVICE_DEFAULT_PORT = '5000'
SERVICE_DEFAULT_DEBUG = False
SERVICE_DEFAULT_LOG_LEVEL = 'DEBUG'
SERVICE_DEFAULT_BASE_URL = 'http://localhost:5000'
SERVICE_DEFAULT_DOMAIN = '127.0.0.1:5000'

SERVICE_LOG_LEVEL_MAP = {
    'debug': logging.DEBUG,
    'info': logging.INFO,
    'warning': logging.WARNING,
    'error': logging.ERROR,
    'critical': logging.CRITICAL,
}

# database variant name and default value
DB_CONFIG_MODULE = 'db'
DB_SQLALCHEMY_URI = 'SQLALCHEMY_DATABASE_URI'
DB_SQLALCHEMY_TRACK_MODIFICATIONS = 'SQLALCHEMY_TRACK_MODIFICATIONS'
DB_SQLALCHEMY_ECHO = 'SQLALCHEMY_ECHO'

DB_DEFAULT_SQLALCHEMY_URI = ''
DB_DEFAULT_SQLALCHEMY_TRACK_MODIFICATIONS = False
DB_DEFAULT_SQLALCHEMY_ECHO = False

# minio variant name
MINIO_CONFIG_MODULE = 'minio'
MINIO_ENDPOINT = 'ENDPOINT'
MINIO_ACCESS_KEY = 'ACCESS_KEY'
MINIO_SECRET_KEY = 'SECRET_KEY'
