apiVersion: v1
kind: Pod
metadata:
  name: taskmanager-pod-template
spec:
  containers:
  - name: flink-main-container
    resources:
      requests:
        ephemeral-storage: 8192Mi
      limits:
        ephemeral-storage: 8192Mi
    volumeMounts:
      - mountPath: /opt/flink/volumes/hostpath
        name: flink-volume-hostpath
      - mountPath: /opt/flink/artifacts
        name: flink-artifact
      - mountPath: /opt/flink/log
        name: flink-logs
      - mountPath: "/data"
        name: nas-pv-storage
      - mountPath: /eflscache
        name: efls-cache
    securityContext:
      runAsUser: 9999
  volumes:
    - name: flink-volume-hostpath
      hostPath:
        path: /tmp
        type: Directory
    - name: flink-artifact
      emptyDir: { }
    - name: flink-logs
      emptyDir: { }
    - name: efls-cache
      emptyDir: { }
    - name: nas-pv-storage
      persistentVolumeClaim:
        claimName: nas-pvc
