"""add comment to user

Revision ID: e73ba161b467
Revises: 3900a6b99e7e
Create Date: 2021-08-11 15:35:10.167377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73ba161b467'
down_revision = '3900a6b99e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('comment', sa.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'comment')
    # ### end Alembic commands ###
